YAS-CA/objects/Code_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>Command__c</fullName>
        <label>Command</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMD_Class_Path__c</fullName>
        <defaultValue>&apos;C:\\&apos;</defaultValue>
        <label>PMD Class Path</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Report_Location__c</fullName>
        <defaultValue>&apos;C:\\&apos;</defaultValue>
        <label>Report Location</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <label>Format Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>codeclimate</fullName>
                    <default>true</default>
                    <label>codeclimate</label>
                </value>
                <value>
                    <fullName>csv</fullName>
                </value>
                <value>
                    <fullName>html</fullName>
                </value>
                <value>
                    <fullName>summaryhtml</fullName>
                </value>
                <value>
                    <fullName>text</fullName>
                </value>
                <value>
                    <fullName>vbhtml</fullName>
                </value>
                <value>
                    <fullName>xml</fullName>
                </value>
                <value>
                    <fullName>yahtml</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rules_Path__c</fullName>
        <defaultValue>&apos;&apos;</defaultValue>
        <label>Rules Path</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_Files_Path__c</fullName>
        <defaultValue>&apos;C:\\&apos;</defaultValue>
        <label>Source Files Path</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Code Analysis</label>
    <nameField>
        <displayFormat>CA-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

YAS-CA/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>XML_Format__c</fullName>
        <label>XML Format</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

YAS-CA/objects/Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_Properties__c</fullName>
        <label>No Of Properties</label>
        <summaryForeignKey>Property__c.Rule__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rule_Set__c</fullName>
        <label>Rule Set</label>
        <referenceTo>Rule_Set__c</referenceTo>
        <relationshipLabel>Rules</relationshipLabel>
        <relationshipName>Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>XML_Format__c</fullName>
        <label>XML Format</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

YAS-CA/objects/Rule_Set__c.object
<CustomObject>
    <fields>
        <fullName>Active_Rules__c</fullName>
        <label>Active Rules</label>
        <summaryFilterItems>
            <field>Rule__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Rule__c.Rule_Set__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Code_Analysis__c</fullName>
        <label>Code Analysis</label>
        <referenceTo>Code_Analysis__c</referenceTo>
        <relationshipLabel>Rule Sets</relationshipLabel>
        <relationshipName>Rule_Sets1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Set</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

YAS-CA/classes/CodeAnalysis.cls
public class CodeAnalysis 
{
    private final String strXML_PROPERTIES = '</properties>';
    
	public static void generate(Id idCode)
    {
        List<String> lstFileName = new List<String>();
        try 
        {
            //get all Rulesets for this code scan
            List<Rule_Set__c> lstRuleSet = [SELECT   id
                                                    ,Name
                                                    ,Active_Rules__c
                                            FROM 	Rule_Set__c 
                                            WHERE 	Code_Analysis__c =:idCode];

            For (Rule_Set__c objRuleSet :lstRuleSet)
            {
                //only generate a file if there are Active rules
                If (objRuleSet.Active_Rules__c > 0)
                {
                    //get all Rules for this RuleSet
                    List<Rule__c> lstRule = [SELECT XML_Format__c
                                                    ,Name
                                                    ,No_Of_Properties__c
                                            FROM 	Rule__c 
                                            WHERE 	Rule_Set__c =:objRuleSet.id
                                            AND 	Active__c = TRUE];
                        
                    XmlStreamWriter w = new XmlStreamWriter();
                    w.writeStartDocument(null, '1.0');

                    //Header info 
                    w.writeStartElement('', 'ruleset', '');
                    w.writeAttribute(null, null, 'name', objRuleSet.Name);
                    w.writeAttribute(null, null, 'xmlns', 'http://pmd.sourceforge.net/ruleset/2.0.0');
                    w.writeAttribute(null, null, 'xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance');
                    w.writeAttribute(null, null, 'xsi:schemaLocation', 'http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd');
                    
                    //Description
                    w.writeStartElement(null, 'description', null);
                    w.writeCharacters('Custom Rule Set file for ' + objRuleSet.Name);
                    w.writeEndElement();

                    //get all XML fields from all Rules
                    For(Rule__c objRule :lstRule)
                    {
                        //HACK! This is simply a placeholder...we will need to do a string replacement later on
                        w.writeCharacters('||' + objRule.Name + '||');                  
                    }
                
                    //End XML elements
                    w.writeEndElement(); 
                    w.writeEndDocument();
                    
                    String strXML = w.getXmlString();
                    
                    //loop through the list again to perform the replace on the string version
                    For(Rule__c objRule :lstRule)
                    {
                        String strXMLRule = objRule.XML_Format__c;
                        String strProperties = '';

                        //check to see if this Rule has properties attached to it
                        If(objRule.No_Of_Properties__c > 0)
                        {
                            //get all Property__c for this Rule
                            List<Property__c> lstProperty = [SELECT XML_Format__c
                                                                    ,Name
                                                             FROM 	Property__c 
                                                             WHERE 	Rule__c =:objRule.id];

                            For(Property__c objProperty: lstProperty)
                            {
                                strProperties += objProperty.XML_Format__c;
                            }   

                            //insert the Property__c's into the appropriate place
                            strXMLRule = strXMLRule.replace('<properties></properties>', '<properties>' + strProperties + '</properties>');                                                          
                        }
                        else 
                        {
                            //no properties exist, so remove the "<properties></properties>" tags
                            strXMLRule = strXMLRule.replace('<properties></properties>', '');     
                        }

                        strXML = strXML.replace('||' + objRule.Name + '||', strXMLRule);              
                    }
                                
                    System.debug(strXML);

                    //Create the document & add the FileName_DTTM.xml to a list
                    lstFileName.add(Utils.createFile(idCode, objRuleSet.Name, strXML)); 

                    w.close();   
                }
            } 
            //update the entire class path of rules
            List<Code_Analysis__c> lstCodeAnalysis = [SELECT id
                                                            ,PMD_Class_Path__c
                                                            ,Rules_Path__c
                                                            ,Command__c
                                                            ,Source_Files_Path__c
                                                            ,Report_Type__c
                                                            ,Report_Location__c
                                                      FROM 	 Code_Analysis__c 
                                                      WHERE  id =:idCode LIMIT 1];
            
            List<Code_Analysis__c> lstCodeAnalysisToUpdate = new List<Code_Analysis__c>();

            for (Code_Analysis__c objCodeAnalysis: lstCodeAnalysis)
            {
                Integer i = 0;

                for (String strFileName: lstFileName)
                {
                    If(i > 0)
                    {
                        objCodeAnalysis.Rules_Path__c += ',' + objCodeAnalysis.PMD_Class_Path__c + '\\' + strFileName;
                    }
                    else
                    {
                        objCodeAnalysis.Rules_Path__c = objCodeAnalysis.PMD_Class_Path__c + '\\' + strFileName;
                    }
                    i++;
                }
                objCodeAnalysis.Command__c = 'pmd.bat' 
                                                + ' -d "' + objCodeAnalysis.Source_Files_Path__c + '"'
                                                + ' -R "' + objCodeAnalysis.Rules_Path__c + '"'
                                                + ' -f ' + objCodeAnalysis.Report_Type__c 
                                                + ' -reportfile "' + objCodeAnalysis.Report_Location__c + '"';
                lstCodeAnalysisToUpdate.add(objCodeAnalysis);
                System.debug('>>>>>>>>' + objCodeAnalysis.Rules_Path__c); 
            } 
            update lstCodeAnalysisToUpdate;                                             
        } 
        catch (Exception ex) 
        {
            
        }
    }
	public static void Doc(Id idCode)
    {
        //Create the document
       /**  Document doc = new Document();
        doc.Name = 'ComplexRR';
        doc.ContentType = 'text/plain';
        doc.Type = 'xml';
        //doc.AuthorId = UserInfo.getUserId();
        doc.FolderId = '00l1t000001MmWdAAK';
        
        //String bodyStr = 'Hello World<Test>Value</Test>';
        Blob body = Blob.valueOf(strXML);
        doc.Body = body;
        insert doc;   
        */       
    } 

    public static String test()
    {
        return 'Works';   
    }
}